name: PROG_ST10082700_MESSI CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      Solution_Name: PROG_ST10082700_MESSI.sln
      Project_Path: PROG_ST10082700_MESSI/PROG_ST10082700_MESSI.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore ${{ env.Solution_Name }}

    - name: Build
      run: dotnet build ${{ env.Solution_Name }} --configuration ${{ matrix.configuration }} --no-restore

    - name: Test
      run: dotnet test ${{ env.Solution_Name }} --configuration ${{ matrix.configuration }} --no-build

    - name: Publish
      if: matrix.configuration == 'Release'
      run: dotnet publish ${{ env.Project_Path }} --configuration ${{ matrix.configuration }} --no-build --output ./publish

    - name: Upload artifact
      if: matrix.configuration == 'Release'
      uses: actions/upload-artifact@v3
      with:
        name: PROG_ST10082700_MESSI-App
        path: ./publish
